export type SimulationCategory =
  | "engineering"
  | "business"
  | "healthcare"
  | "trades"
  | "technology"
  | "law"
  | "science"
  | "life-advice"
  | "creative-design";

export type EnvironmentKind =
  | "mech-lab"
  | "construction-site"
  | "circuit-board"
  | "chem-plant"
  | "factory-floor"
  | "office-desk"
  | "hospital-room"
  | "server-room"
  | "data-viz"
  | "courtroom"
  | "kitchen"
  | "rooftop-solar"
  | "wind-turbine"
  | "spa"
  | "brain-lab"
  | "observatory"
  | "bio-lab"
  | "ocean-research";

export type SimulationDefinition = {
  slug: string;
  title: string;
  category: SimulationCategory;
  tagline: string;
  description: string;
  topics: string[];
  environment: EnvironmentKind;
  available: boolean;
};

export const CATEGORY_LABELS: Record<SimulationCategory, string> = {
  engineering: "Engineering",
  business: "Business",
  healthcare: "Healthcare",
  trades: "Trades",
  technology: "Technology",
  law: "Law",
  science: "Science & Research",
  "life-advice": "Life & Career Advice",
  "creative-design": "Creative & Design",
};

export const SIMULATIONS: SimulationDefinition[] = [
  // ENGINEERING
  {
    slug: "mechanical-engineering",
    title: "Mechanical Engineer",
    category: "engineering",
    tagline: "Test prototypes, fix overheating robots, design simple machines.",
    description:
      "Step into a product testing lab and solve real mechanical problems — from a robot arm overheating to choosing the right pulley system.",
    topics: [
      "Product testing lab",
      "Robotic arm overheating",
      "Levers and pulleys",
      "Gears and torque",
      "Forces and motion",
      "Energy efficiency",
      "Material selection",
      "Prototype improvement",
    ],
    environment: "mech-lab",
    available: true,
  },
  {
    slug: "civil-engineering",
    title: "Civil Engineer",
    category: "engineering",
    tagline: "Design bridges, plan cities, keep infrastructure standing.",
    description:
      "Take on bridge designs, building foundations, traffic flow, and earthquake resistance challenges.",
    topics: [
      "Bridge design",
      "Roadway planning",
      "Building foundations",
      "Earthquake resistance",
      "Traffic flow",
      "Stormwater drainage",
      "City planning",
    ],
    environment: "construction-site",
    available: true,
  },
  {
    slug: "electrical-engineering",
    title: "Electrical Engineer",
    category: "engineering",
    tagline: "Wire circuits, troubleshoot devices, power renewable systems.",
    description:
      "Solve real electrical problems — basic circuits, sensors, batteries, signal flow, and renewable power.",
    topics: [
      "Basic circuits",
      "Voltage and current",
      "Resistance",
      "Power systems",
      "Sensors",
      "Renewable energy",
      "Circuit troubleshooting",
    ],
    environment: "circuit-board",
    available: true,
  },
  {
    slug: "chemical-engineering",
    title: "Chemical Engineer",
    category: "engineering",
    tagline: "Run reactors, scale lab processes, keep plants safe.",
    description:
      "Operate mixing systems, manage heat transfer, and keep chemical plants safe and consistent.",
    topics: [
      "Mixing systems",
      "Heat transfer",
      "Plant safety",
      "Filtration",
      "Quality control",
      "Process efficiency",
      "Contamination prevention",
    ],
    environment: "chem-plant",
    available: true,
  },
  {
    slug: "aerospace-engineering",
    title: "Aerospace Engineer",
    category: "engineering",
    tagline: "Test wings, plan launches, push the limits of flight.",
    description:
      "Tackle lift and drag, rocket stability, fuel efficiency, and spacecraft heat protection.",
    topics: [
      "Lift and drag",
      "Rocket stability",
      "Wing design",
      "Fuel efficiency",
      "Wind tunnel testing",
      "Payload tradeoffs",
    ],
    environment: "mech-lab",
    available: true,
  },
  {
    slug: "biomedical-engineering",
    title: "Biomedical Engineer",
    category: "engineering",
    tagline: "Design prosthetics, test devices, build for patients.",
    description:
      "Create prosthetics, test medical devices, and design accessible, human-centered tools.",
    topics: [
      "Prosthetic design",
      "Medical device testing",
      "Biomechanics",
      "Wearable sensors",
      "Patient safety",
      "Accessibility design",
    ],
    environment: "mech-lab",
    available: true,
  },
  {
    slug: "industrial-engineering",
    title: "Industrial Engineer",
    category: "engineering",
    tagline: "Find bottlenecks, redesign workflows, eliminate waste.",
    description:
      "Improve factory workflows, schedule production, and balance cost vs. efficiency.",
    topics: [
      "Factory workflow",
      "Process improvement",
      "Reducing waste",
      "Scheduling",
      "Bottlenecks",
      "Lean systems",
    ],
    environment: "factory-floor",
    available: true,
  },
  {
    slug: "environmental-engineering",
    title: "Environmental Engineer",
    category: "engineering",
    tagline: "Clean water, control pollution, build climate resilience.",
    description:
      "Design clean water systems, control pollution, and respond to climate impacts.",
    topics: [
      "Clean water systems",
      "Air quality",
      "Waste management",
      "Pollution control",
      "Sustainable materials",
      "Climate resilience",
    ],
    environment: "chem-plant",
    available: true,
  },
  {
    slug: "software-engineering",
    title: "Software Engineer",
    category: "engineering",
    tagline: "Debug, ship features, fix automations gone wrong.",
    description:
      "Triage bugs, prioritize features, and decide when to ship in real software situations.",
    topics: [
      "Debugging",
      "User experience problems",
      "Feature prioritization",
      "AI feature misbehavior",
      "Memory leaks",
      "Security basics",
      "Bug triage",
    ],
    environment: "server-room",
    available: true,
  },

  // BUSINESS
  {
    slug: "entrepreneurship",
    title: "Entrepreneur",
    category: "business",
    tagline: "Test ideas, find customers, run the startup gauntlet.",
    description:
      "Validate startup ideas, find product-market fit, price your product, and pitch investors.",
    topics: [
      "Startup idea testing",
      "Business model design",
      "Pricing",
      "Customer discovery",
      "Pitching",
      "Hiring early team",
      "Revenue model",
    ],
    environment: "office-desk",
    available: true,
  },
  {
    slug: "marketing",
    title: "Marketing Strategist",
    category: "business",
    tagline: "Run campaigns across TikTok, Instagram, and beyond.",
    description:
      "Plan campaigns, test ad creative, segment audiences, and measure ROI across channels.",
    topics: [
      "Social media strategy",
      "Ad creative testing",
      "Brand positioning",
      "Audience segmentation",
      "Influencer partnerships",
      "Email marketing",
      "Measuring ROI",
    ],
    environment: "data-viz",
    available: true,
  },
  {
    slug: "finance-investing",
    title: "Financial Advisor",
    category: "business",
    tagline: "Build portfolios, manage risk, advise real clients.",
    description:
      "Profile clients, choose portfolios, and explain risk clearly when markets move.",
    topics: [
      "Client risk profile",
      "Portfolio choices",
      "Diversification",
      "Market volatility",
      "Stock research",
      "Ethical advice",
      "Rebalancing",
    ],
    environment: "data-viz",
    available: true,
  },
  {
    slug: "accounting",
    title: "Accountant",
    category: "business",
    tagline: "Catch fraud, fix the books, keep the business honest.",
    description:
      "Read P&Ls, track cash flow, spot fraud red flags, and support business decisions.",
    topics: [
      "Profit and loss",
      "Cash flow",
      "Break-even analysis",
      "Budget variance",
      "Fraud red flags",
      "Tax basics",
      "Internal controls",
    ],
    environment: "office-desk",
    available: true,
  },
  {
    slug: "management",
    title: "Manager",
    category: "business",
    tagline: "Lead teams, resolve conflict, make tough calls.",
    description:
      "Run a team — handle hiring, delegation, conflict, and crisis with clarity.",
    topics: [
      "Team leadership",
      "Conflict resolution",
      "Hiring decisions",
      "Delegation",
      "Performance feedback",
      "Workplace culture",
      "Crisis response",
    ],
    environment: "office-desk",
    available: true,
  },
  {
    slug: "sales",
    title: "Sales Professional",
    category: "business",
    tagline: "Run discovery calls, handle objections, close deals.",
    description:
      "Conduct discovery calls, handle objections, build trust, and close real deals.",
    topics: [
      "Discovery calls",
      "Handling objections",
      "Building trust",
      "Closing deals",
      "Cold outreach",
      "Negotiation",
      "Customer retention",
    ],
    environment: "office-desk",
    available: true,
  },

  // HEALTHCARE
  {
    slug: "nursing",
    title: "Nurse",
    category: "healthcare",
    tagline: "Triage patients, manage meds, keep everyone safe.",
    description:
      "Run patient triage, monitor vitals, hand off cases, and stay calm under pressure.",
    topics: [
      "Patient triage",
      "Vital signs",
      "Medication safety",
      "Patient communication",
      "Team handoffs",
      "Infection control",
      "Emergency prioritization",
    ],
    environment: "hospital-room",
    available: true,
  },
  {
    slug: "physician",
    title: "Physician",
    category: "healthcare",
    tagline: "Diagnose, plan care, decide when to refer.",
    description:
      "Listen to symptoms, ask the right questions, and choose the right next step in care.",
    topics: [
      "Diagnosing symptoms",
      "Patient questions",
      "Care planning",
      "Referral decisions",
      "Preventive care",
      "Ethical dilemmas",
      "Emergency judgment",
    ],
    environment: "hospital-room",
    available: true,
  },
  {
    slug: "physician-assistant",
    title: "Physician Assistant",
    category: "healthcare",
    tagline: "Run intake, escalate carefully, explain treatment.",
    description:
      "Manage patient intake, treatment planning, and clear communication in urgent and rural care.",
    topics: [
      "Patient intake",
      "Follow-up care",
      "Treatment planning",
      "Escalating concerns",
      "Patient education",
      "Urgent care scenarios",
    ],
    environment: "hospital-room",
    available: true,
  },
  {
    slug: "pharmacist",
    title: "Pharmacist",
    category: "healthcare",
    tagline: "Catch drug interactions, counsel patients, keep dosing safe.",
    description:
      "Review medications, catch interactions, counsel patients, and verify dosing.",
    topics: [
      "Medication review",
      "Drug interactions",
      "Patient counseling",
      "Dosage clarification",
      "Vaccine questions",
      "Prescription accuracy",
    ],
    environment: "hospital-room",
    available: true,
  },
  {
    slug: "physical-therapist",
    title: "Physical Therapist",
    category: "healthcare",
    tagline: "Plan rehab, motivate patients, track recovery.",
    description:
      "Assess injuries, plan progressions, and keep patients moving forward through setbacks.",
    topics: [
      "Injury assessment",
      "Rehab planning",
      "Patient motivation",
      "Exercise progression",
      "Recovery setbacks",
      "Sports injuries",
    ],
    environment: "hospital-room",
    available: true,
  },
  {
    slug: "radiologist",
    title: "Radiologist",
    category: "healthcare",
    tagline: "Read imaging, prioritize urgent scans, catch the missed detail.",
    description:
      "Spot patterns in scans, prioritize emergency imaging, and communicate findings clearly.",
    topics: [
      "Imaging clues",
      "Prioritizing scans",
      "Communicating findings",
      "Pattern recognition",
      "Emergency imaging",
      "Avoiding missed details",
    ],
    environment: "hospital-room",
    available: true,
  },
  {
    slug: "dentist",
    title: "Dentist",
    category: "healthcare",
    tagline: "Prevent cavities, calm anxious patients, plan treatments.",
    description:
      "Plan treatments, calm anxious patients, and balance cosmetic vs. health decisions.",
    topics: [
      "Cavity prevention",
      "Patient anxiety",
      "Treatment planning",
      "X-ray basics",
      "Emergency dental pain",
      "Child patient communication",
    ],
    environment: "hospital-room",
    available: true,
  },
  {
    slug: "veterinarian",
    title: "Veterinarian",
    category: "healthcare",
    tagline: "Read animal symptoms, talk with owners, handle emergencies.",
    description:
      "Diagnose animals from limited clues, communicate with owners, and prep for surgery.",
    topics: [
      "Animal symptoms",
      "Owner communication",
      "Exam priorities",
      "Emergency animal care",
      "Vaccinations",
      "Surgery prep",
    ],
    environment: "hospital-room",
    available: true,
  },
  {
    slug: "psychologist",
    title: "Psychologist",
    category: "healthcare",
    tagline: "Listen, ask, and support — without crossing lines.",
    description:
      "Practice listening, supportive questioning, and ethical decisions in therapy.",
    topics: [
      "Listening skills",
      "Supportive questions",
      "Stress management",
      "Ethical boundaries",
      "Referral decisions",
      "Crisis escalation",
    ],
    environment: "office-desk",
    available: true,
  },
  {
    slug: "speech-language-pathologist",
    title: "Speech-Language Pathologist",
    category: "healthcare",
    tagline: "Help students communicate, plan therapy, partner with families.",
    description:
      "Plan therapy, support students, and use assistive tools to grow communication.",
    topics: [
      "Speech development",
      "Communication barriers",
      "Therapy planning",
      "Parent communication",
      "Swallowing safety",
      "Assistive tools",
    ],
    environment: "office-desk",
    available: true,
  },
  {
    slug: "health-services-manager",
    title: "Health Services Manager",
    category: "healthcare",
    tagline: "Run hospital ops, balance budgets, keep patients flowing.",
    description:
      "Schedule staff, manage budgets, and keep departments coordinated under pressure.",
    topics: [
      "Hospital operations",
      "Staff scheduling",
      "Patient flow",
      "Budget decisions",
      "Quality improvement",
      "Resource shortages",
    ],
    environment: "office-desk",
    available: true,
  },

  // TRADES
  {
    slug: "electrician",
    title: "Electrician",
    category: "trades",
    tagline: "Trace faults, install safely, keep code in mind.",
    description:
      "Diagnose wiring problems, work with breakers, and plan installations safely.",
    topics: [
      "Wiring problems",
      "Circuit safety",
      "Breaker panels",
      "Reading diagrams",
      "Troubleshooting outlets",
      "Load management",
      "Code awareness",
    ],
    environment: "circuit-board",
    available: true,
  },
  {
    slug: "plumber",
    title: "Plumber",
    category: "trades",
    tagline: "Fix leaks, restore pressure, prevent bigger damage.",
    description:
      "Find leaks, fix drains, install fixtures, and handle emergencies cleanly.",
    topics: [
      "Pipe leaks",
      "Water pressure",
      "Drain clogs",
      "Fixture installation",
      "Emergency repairs",
      "Customer estimates",
    ],
    environment: "construction-site",
    available: true,
  },
  {
    slug: "hvac-technician",
    title: "HVAC Technician",
    category: "trades",
    tagline: "Fix heating, cooling, and airflow — fast.",
    description:
      "Troubleshoot heating, cooling, airflow, and thermostats in real homes and businesses.",
    topics: [
      "Heating issues",
      "Cooling issues",
      "Airflow problems",
      "Thermostat troubleshooting",
      "Refrigerant basics",
      "Energy efficiency",
    ],
    environment: "construction-site",
    available: true,
  },
  {
    slug: "carpenter",
    title: "Carpenter",
    category: "trades",
    tagline: "Measure twice, cut once, build it strong.",
    description:
      "Read plans, choose materials, and frame structures that last.",
    topics: [
      "Measuring and cutting",
      "Framing",
      "Material selection",
      "Reading plans",
      "Tool safety",
      "Structural support",
    ],
    environment: "construction-site",
    available: true,
  },
  {
    slug: "construction-equipment-operator",
    title: "Construction Equipment Operator",
    category: "trades",
    tagline: "Move dirt, place loads, run heavy machines safely.",
    description:
      "Plan digging strategies, place loads, and adapt to weather and terrain on site.",
    topics: [
      "Site safety",
      "Equipment positioning",
      "Digging strategy",
      "Load movement",
      "Terrain challenges",
      "Weather delays",
    ],
    environment: "construction-site",
    available: true,
  },
  {
    slug: "solar-installer",
    title: "Solar Photovoltaic Installer",
    category: "trades",
    tagline: "Place panels, chase the sun, deliver clean power.",
    description:
      "Plan panel placement, work with sun angles, wire safely, and meet customer goals.",
    topics: [
      "Panel placement",
      "Roof safety",
      "Sun angle",
      "Wiring basics",
      "Customer energy goals",
      "Weather constraints",
    ],
    environment: "rooftop-solar",
    available: true,
  },
  {
    slug: "wind-turbine-technician",
    title: "Wind Turbine Technician",
    category: "trades",
    tagline: "Climb high, troubleshoot turbines, work safe in any weather.",
    description:
      "Inspect turbines, troubleshoot mechanical and electrical faults, and plan safe repairs.",
    topics: [
      "Turbine inspection",
      "Climbing safety",
      "Mechanical troubleshooting",
      "Electrical troubleshooting",
      "Weather conditions",
      "Emergency shutdowns",
    ],
    environment: "wind-turbine",
    available: true,
  },
  {
    slug: "industrial-maintenance-technician",
    title: "Industrial Maintenance Tech",
    category: "trades",
    tagline: "Stop downtime, swap parts, lock out hazards.",
    description:
      "Diagnose machine breakdowns, follow safe lockout, and minimize production downtime.",
    topics: [
      "Machine breakdowns",
      "Preventive maintenance",
      "Sensors and controls",
      "Conveyor systems",
      "Safety lockout",
      "Production downtime",
    ],
    environment: "factory-floor",
    available: true,
  },
  {
    slug: "culinary-chef",
    title: "Culinary Chef",
    category: "trades",
    tagline: "Time the kitchen, plate beautifully, survive the rush.",
    description:
      "Manage timing, substitute ingredients, plate dishes, and handle the dinner rush.",
    topics: [
      "Kitchen timing",
      "Menu planning",
      "Ingredient substitution",
      "Food safety",
      "Customer complaints",
      "Rush-hour pressure",
    ],
    environment: "kitchen",
    available: true,
  },
  {
    slug: "esthetician",
    title: "Esthetician",
    category: "trades",
    tagline: "Assess skin, choose treatments, build a loyal clientele.",
    description:
      "Consult clients, choose safe treatments, and recommend ethically.",
    topics: [
      "Skin assessment",
      "Client consultation",
      "Treatment selection",
      "Product safety",
      "Sanitation",
      "Ethical recommendations",
    ],
    environment: "spa",
    available: true,
  },

  // TECHNOLOGY
  {
    slug: "artificial-intelligence",
    title: "AI Engineer",
    category: "technology",
    tagline: "Tame chatbots, catch bias, keep AI useful and safe.",
    description:
      "Tune chatbot behavior, test prompts, catch bias, and add the right guardrails.",
    topics: [
      "AI chatbot behavior",
      "Prompt testing",
      "Bias detection",
      "Automation mistakes",
      "Training data quality",
      "Safety guardrails",
    ],
    environment: "data-viz",
    available: true,
  },
  {
    slug: "cybersecurity",
    title: "Cybersecurity Analyst",
    category: "technology",
    tagline: "Spot phishing, stop intrusions, protect real users.",
    description:
      "Detect phishing, respond to incidents, and harden systems against social engineering.",
    topics: [
      "Phishing detection",
      "Password security",
      "Suspicious logins",
      "Incident response",
      "Social engineering",
      "Risk assessment",
    ],
    environment: "server-room",
    available: true,
  },
  {
    slug: "information-technology",
    title: "IT Specialist",
    category: "technology",
    tagline: "Run the help desk, fix devices, keep work flowing.",
    description:
      "Triage tickets, set up devices, troubleshoot networks, and decide when to escalate.",
    topics: [
      "Help desk tickets",
      "Device setup",
      "Network troubleshooting",
      "Account access",
      "Cloud tools",
      "Escalation decisions",
    ],
    environment: "office-desk",
    available: true,
  },
  {
    slug: "data-analyst",
    title: "Data Analyst",
    category: "technology",
    tagline: "Read dashboards, find the real story, recommend action.",
    description:
      "Read dashboards, clean data, and turn patterns into clear business recommendations.",
    topics: [
      "Reading dashboards",
      "Finding patterns",
      "Misleading metrics",
      "Cleaning data",
      "Explaining insights",
      "Chart selection",
    ],
    environment: "data-viz",
    available: true,
  },
  {
    slug: "quantum-computing",
    title: "Quantum Computing Researcher",
    category: "technology",
    tagline: "Choose the right use case, explain quantum simply.",
    description:
      "Pick practical use cases, compare classical vs. quantum, and explain it without jargon.",
    topics: [
      "Quantum concepts",
      "Practical use cases",
      "Classical vs. quantum",
      "Error challenges",
      "Hardware limitations",
      "Future applications",
    ],
    environment: "data-viz",
    available: true,
  },
  {
    slug: "saas-product-builder",
    title: "SaaS Product Builder",
    category: "technology",
    tagline: "Prioritize features, fix churn, grow the product.",
    description:
      "Make feature calls, improve onboarding, reduce churn, and listen to users.",
    topics: [
      "Product features",
      "User feedback",
      "Subscription pricing",
      "Onboarding",
      "Churn reduction",
      "Feature prioritization",
    ],
    environment: "office-desk",
    available: true,
  },
  {
    slug: "ux-ui-designer",
    title: "UX / UI Designer",
    category: "technology",
    tagline: "Design clear flows, fix frustration, raise conversion.",
    description:
      "Map flows, find friction, test prototypes, and design for accessibility on every screen.",
    topics: [
      "User flow",
      "Accessibility",
      "Layout decisions",
      "Mobile usability",
      "Visual hierarchy",
      "Conversion improvement",
    ],
    environment: "office-desk",
    available: true,
  },
  {
    slug: "cloud-devops",
    title: "Cloud / DevOps Engineer",
    category: "technology",
    tagline: "Keep servers up, scale traffic, control cloud cost.",
    description:
      "Handle outages, scale traffic, monitor alerts, and keep cloud bills sane.",
    topics: [
      "Server reliability",
      "Scaling traffic",
      "Deployment issues",
      "Cloud cost control",
      "Monitoring alerts",
      "Incident response",
    ],
    environment: "server-room",
    available: true,
  },

  // LAW
  {
    slug: "lawyer",
    title: "Lawyer",
    category: "law",
    tagline: "Question witnesses, handle objections, build the case.",
    description:
      "Step into a courtroom — examine witnesses, handle objections, and reason through evidence and ethics.",
    topics: [
      "Witness questioning",
      "Cross-examination",
      "Opening statement strategy",
      "Objection handling",
      "Evidence review",
      "Contract dispute",
      "Client interview",
      "Negotiation",
      "Ethics",
    ],
    environment: "courtroom",
    available: true,
  },
  {
    slug: "defense-lawyer",
    title: "Defense Attorney",
    category: "law",
    tagline: "Protect your client's rights, challenge the evidence, argue reasonable doubt.",
    description:
      "You represent the accused. Challenge the prosecution's evidence, protect constitutional rights, and find the argument that wins in court.",
    topics: [
      "Reasonable doubt",
      "Suppressing evidence",
      "Client rights",
      "Cross-examination",
      "Plea deals",
      "Jury selection",
      "Constitutional violations",
      "Appeals strategy",
    ],
    environment: "courtroom",
    available: true,
  },
  {
    slug: "prosecutor",
    title: "Prosecutor",
    category: "law",
    tagline: "Build the case, prove guilt beyond reasonable doubt.",
    description:
      "Represent the state — gather evidence, decide what to charge, and prove your case to a jury while staying ethical.",
    topics: [
      "Charging decisions",
      "Evidence presentation",
      "Witness credibility",
      "Burden of proof",
      "Plea negotiations",
      "Jury instructions",
      "Prosecutorial ethics",
      "Victim advocacy",
    ],
    environment: "courtroom",
    available: true,
  },
  {
    slug: "police-officer",
    title: "Police Officer",
    category: "law",
    tagline: "Respond, assess, and de-escalate in high-pressure situations.",
    description:
      "Handle dispatch calls, traffic stops, and community incidents — applying the law while protecting rights and keeping the peace.",
    topics: [
      "Traffic stops",
      "De-escalation",
      "Search and seizure",
      "Probable cause",
      "Use of force policy",
      "Dispatch triage",
      "Community relations",
      "Report writing",
    ],
    environment: "courtroom",
    available: true,
  },
  {
    slug: "corporate-lawyer",
    title: "Corporate Lawyer",
    category: "law",
    tagline: "Draft deals, spot liability, keep the business clean.",
    description:
      "Review contracts, advise executives, close mergers, and catch the clause that could blow up the deal.",
    topics: [
      "Contract review",
      "Mergers and acquisitions",
      "Liability assessment",
      "Intellectual property",
      "Non-disclosure agreements",
      "Regulatory compliance",
      "Shareholder disputes",
      "Due diligence",
    ],
    environment: "office-desk",
    available: true,
  },
  {
    slug: "judge",
    title: "Judge",
    category: "law",
    tagline: "Rule on objections, weigh evidence, deliver fair decisions.",
    description:
      "Preside over hearings, manage courtroom conduct, apply the law to complex facts, and issue rulings that hold up on appeal.",
    topics: [
      "Ruling on objections",
      "Sentencing guidelines",
      "Evidence admissibility",
      "Jury instructions",
      "Bench trials",
      "Contempt of court",
      "Judicial impartiality",
      "Appeals considerations",
    ],
    environment: "courtroom",
    available: true,
  },
  {
    slug: "detective",
    title: "Detective",
    category: "law",
    tagline: "Follow the evidence, interview suspects, solve the case.",
    description:
      "Investigate crime scenes, interview witnesses, connect the dots, and build a case that will hold up in court.",
    topics: [
      "Crime scene analysis",
      "Suspect interviews",
      "Evidence chain of custody",
      "Witness credibility",
      "Warrant applications",
      "Case prioritization",
      "Undercover decisions",
      "Forensic basics",
    ],
    environment: "office-desk",
    available: true,
  },
  {
    slug: "federal-agent",
    title: "Federal Agent",
    category: "law",
    tagline: "Investigate federal crimes, coordinate agencies, protect national security.",
    description:
      "Handle federal investigations — from financial fraud to cybercrime — coordinating with local law enforcement and navigating classified protocols.",
    topics: [
      "Federal jurisdiction",
      "Surveillance authorization",
      "Interagency coordination",
      "Cybercrime investigation",
      "Financial fraud detection",
      "Informant management",
      "National security protocols",
      "Testifying in federal court",
    ],
    environment: "server-room",
    available: true,
  },

  // BUSINESS — TRADING / FINANCE EXTENSIONS
  {
    slug: "stock-trader",
    title: "Stock Trader",
    category: "business",
    tagline: "Read the market, time entries, manage your risk.",
    description:
      "Analyze price action, interpret earnings reports, set stop-losses, and decide when to hold or exit positions.",
    topics: [
      "Reading price charts",
      "Earnings surprises",
      "Risk management",
      "Stop-loss strategy",
      "Market volatility",
      "Sector rotation",
      "Order types",
      "Short selling basics",
    ],
    environment: "data-viz",
    available: true,
  },
  {
    slug: "crypto-analyst",
    title: "Cryptocurrency Analyst",
    category: "business",
    tagline: "Navigate wallets, protocols, and wild volatility.",
    description:
      "Evaluate blockchain projects, manage wallet security, interpret tokenomics, and make calls in a 24/7 market.",
    topics: [
      "Blockchain basics",
      "Wallet security",
      "Tokenomics",
      "DeFi protocols",
      "Market volatility",
      "Regulatory risk",
      "NFT valuations",
      "On-chain analysis",
    ],
    environment: "data-viz",
    available: true,
  },
  {
    slug: "economist",
    title: "Economist",
    category: "business",
    tagline: "Read macro signals, forecast trends, advise policy.",
    description:
      "Interpret GDP data, model inflation, analyze labor markets, and advise on economic policy with real-world tradeoffs.",
    topics: [
      "Inflation and interest rates",
      "GDP interpretation",
      "Labor market signals",
      "Supply and demand",
      "Trade policy",
      "Recession indicators",
      "Fiscal vs monetary policy",
      "Economic forecasting",
    ],
    environment: "data-viz",
    available: true,
  },
  {
    slug: "investment-banker",
    title: "Investment Banker",
    category: "business",
    tagline: "Structure deals, value companies, advise on M&A.",
    description:
      "Work on high-stakes deals — value a company, structure a merger, build a pitch deck, and navigate client pressure.",
    topics: [
      "Company valuation",
      "Mergers and acquisitions",
      "Pitch decks",
      "Deal structuring",
      "Due diligence",
      "Leveraged buyouts",
      "IPO preparation",
      "Client negotiation",
    ],
    environment: "office-desk",
    available: true,
  },

  // TECHNOLOGY — NEW FRONTIERS
  {
    slug: "biocomputing",
    title: "Biocomputing Researcher",
    category: "technology",
    tagline: "Program DNA, design bio-circuits, push the edge of computing.",
    description:
      "Design DNA-based logic gates, evaluate biological storage systems, and navigate the ethical edge of programming living cells.",
    topics: [
      "DNA data storage",
      "Biological logic gates",
      "CRISPR applications",
      "Synthetic biology",
      "Error rates in bio-systems",
      "Biocomputing ethics",
      "Protein folding",
      "Cell-based sensors",
    ],
    environment: "chem-plant",
    available: true,
  },
  {
    slug: "fusion-engineer",
    title: "Fusion Energy Engineer",
    category: "technology",
    tagline: "Contain plasma, hit ignition, build tomorrow's power source.",
    description:
      "Operate a tokamak simulation, manage plasma containment, optimize fuel cycles, and troubleshoot instabilities on the path to clean energy.",
    topics: [
      "Plasma containment",
      "Magnetic field configuration",
      "Fuel cycle optimization",
      "Ignition thresholds",
      "Tritium handling",
      "Energy gain ratio",
      "Instability events",
      "Safety shutdowns",
    ],
    environment: "chem-plant",
    available: true,
  },

  // SCIENCE & RESEARCH
  {
    slug: "neuroscientist",
    title: "Neuroscientist",
    category: "science",
    tagline: "Map the brain, decode behavior, untangle how we think.",
    description:
      "Design experiments, interpret neural imaging data, and figure out what brain regions and chemicals drive behavior.",
    topics: [
      "Brain regions and function",
      "Neural imaging",
      "Neurotransmitters",
      "Memory and learning",
      "Brain plasticity",
      "Mental health connections",
      "Experimental design",
      "Drug effects on the brain",
    ],
    environment: "brain-lab",
    available: true,
  },
  {
    slug: "chemist",
    title: "Chemist",
    category: "science",
    tagline: "Run reactions, balance equations, discover new compounds.",
    description:
      "Conduct lab experiments, interpret reaction outcomes, identify unknowns, and apply chemistry to real-world problems.",
    topics: [
      "Chemical reactions",
      "Balancing equations",
      "Atomic structure",
      "Acids and bases",
      "Lab safety",
      "Organic chemistry basics",
      "Identifying compounds",
      "Industrial chemistry",
    ],
    environment: "chem-plant",
    available: true,
  },
  {
    slug: "physicist",
    title: "Physicist",
    category: "science",
    tagline: "Measure the invisible, model the universe, test your theories.",
    description:
      "Apply physics principles to real experiments — from mechanics to thermodynamics to electromagnetism and relativity.",
    topics: [
      "Newton's laws",
      "Energy and work",
      "Electromagnetism",
      "Thermodynamics",
      "Waves and optics",
      "Relativity basics",
      "Experimental error",
      "Applied physics",
    ],
    environment: "mech-lab",
    available: true,
  },
  {
    slug: "astronomer",
    title: "Astronomer",
    category: "science",
    tagline: "Observe the cosmos, classify stars, explain what the data says.",
    description:
      "Analyze telescope data, classify celestial objects, interpret spectra, and reason about the scale of the universe.",
    topics: [
      "Star classification",
      "Light spectra",
      "Galaxy types",
      "Black holes",
      "Exoplanet detection",
      "Telescope data",
      "Cosmic distances",
      "The Big Bang",
    ],
    environment: "observatory",
    available: true,
  },
  {
    slug: "mathematician",
    title: "Mathematician",
    category: "science",
    tagline: "Find patterns, prove ideas, apply math where it matters.",
    description:
      "Solve real-world problems with mathematical reasoning — from statistics and probability to modeling and proof.",
    topics: [
      "Probability and statistics",
      "Number theory",
      "Mathematical modeling",
      "Logic and proof",
      "Algebra and functions",
      "Geometry",
      "Cryptography basics",
      "Data interpretation",
    ],
    environment: "data-viz",
    available: true,
  },
  {
    slug: "biologist",
    title: "Biologist",
    category: "science",
    tagline: "Study life, run field experiments, unlock how living systems work.",
    description:
      "Investigate ecosystems, analyze cell biology, design controlled experiments, and interpret findings from the wild to the lab.",
    topics: [
      "Cell biology",
      "Genetics and heredity",
      "Ecosystems and ecology",
      "Evolution",
      "Photosynthesis and respiration",
      "Scientific method",
      "Microbiology basics",
      "Conservation decisions",
    ],
    environment: "bio-lab",
    available: true,
  },
  {
    slug: "geologist",
    title: "Geologist",
    category: "science",
    tagline: "Read the rocks, predict hazards, find what the earth is hiding.",
    description:
      "Interpret rock formations, assess earthquake and volcano risk, analyze soil and sediment, and advise on land use and resource extraction.",
    topics: [
      "Rock and mineral identification",
      "Plate tectonics",
      "Earthquake risk",
      "Volcano monitoring",
      "Soil analysis",
      "Fossil interpretation",
      "Natural resource mapping",
      "Erosion and landslides",
    ],
    environment: "construction-site",
    available: true,
  },
  {
    slug: "quantum-researcher",
    title: "Quantum Researcher",
    category: "science",
    tagline: "Work at the edge of physics — where particles break the rules.",
    description:
      "Explore quantum phenomena like superposition, entanglement, and tunneling through experiment design and real research tradeoffs.",
    topics: [
      "Superposition",
      "Entanglement",
      "Quantum tunneling",
      "Wave-particle duality",
      "Uncertainty principle",
      "Quantum measurement",
      "Quantum cryptography",
      "Practical quantum devices",
    ],
    environment: "data-viz",
    available: true,
  },
  {
    slug: "oceanographer",
    title: "Oceanographer",
    category: "science",
    tagline: "Dive deep, map currents, protect what's beneath the surface.",
    description:
      "Collect ocean data, model currents and temperatures, study marine ecosystems, and advise on climate and conservation.",
    topics: [
      "Ocean currents",
      "Marine ecosystems",
      "Deep sea exploration",
      "Ocean chemistry",
      "Climate and oceans",
      "Coral reef health",
      "Sonar and mapping",
      "Plastic pollution impact",
    ],
    environment: "ocean-research",
    available: true,
  },

  // LIFE & CAREER ADVICE
  {
    slug: "tax-advisor",
    title: "Tax Advisor",
    category: "life-advice",
    tagline: "File correctly, find deductions, avoid costly mistakes.",
    description:
      "Navigate tax forms, identify deductions, understand tax brackets, and make decisions that keep more money in your pocket legally.",
    topics: [
      "Filing status",
      "Deductions vs credits",
      "W-2 vs 1099",
      "Tax brackets",
      "Student loan interest",
      "Dependent rules",
      "IRS deadlines",
      "Audit red flags",
    ],
    environment: "office-desk",
    available: true,
  },
  {
    slug: "budget-counselor",
    title: "Budget Counselor",
    category: "life-advice",
    tagline: "Track spending, cut waste, build a plan that actually works.",
    description:
      "Build a realistic budget, identify spending leaks, prioritize expenses, and make tradeoffs that align with real financial goals.",
    topics: [
      "Income and expenses",
      "50/30/20 rule",
      "Emergency fund",
      "Fixed vs variable costs",
      "Discretionary spending",
      "Debt repayment",
      "Savings goals",
      "Budget apps and tools",
    ],
    environment: "office-desk",
    available: true,
  },
  {
    slug: "personal-investing",
    title: "Personal Investing Advisor",
    category: "life-advice",
    tagline: "Choose accounts, grow wealth, understand risk at every age.",
    description:
      "Learn how to start investing — from choosing accounts to understanding index funds, compound interest, and risk tolerance.",
    topics: [
      "Index funds vs stocks",
      "Roth IRA and 401k",
      "Compound interest",
      "Risk tolerance",
      "Dollar-cost averaging",
      "Diversification",
      "When to start investing",
      "Avoiding common mistakes",
    ],
    environment: "data-viz",
    available: true,
  },
  {
    slug: "insurance-agent",
    title: "Insurance Agent",
    category: "life-advice",
    tagline: "Match people to the right coverage — not too little, not too much.",
    description:
      "Understand the types of insurance people need — health, auto, renters, life — and help clients make smart coverage decisions.",
    topics: [
      "Health insurance basics",
      "Deductibles vs premiums",
      "Auto insurance",
      "Renters and homeowners insurance",
      "Life insurance types",
      "Liability coverage",
      "Claim processes",
      "Underinsured vs overinsured",
    ],
    environment: "office-desk",
    available: true,
  },
  {
    slug: "retirement-planner",
    title: "Retirement Planner",
    category: "life-advice",
    tagline: "Start early, stay consistent, retire with enough.",
    description:
      "Map out a retirement strategy — when to start, how much to save, what accounts to use, and how to make the money last.",
    topics: [
      "401k and employer match",
      "Social security timing",
      "Safe withdrawal rate",
      "Inflation impact",
      "Roth vs traditional accounts",
      "Sequence of returns risk",
      "Required minimum distributions",
      "Retirement age tradeoffs",
    ],
    environment: "office-desk",
    available: true,
  },
  {
    slug: "resume-coach",
    title: "Resume Coach",
    category: "life-advice",
    tagline: "Write it sharp, cut the fluff, get the interview.",
    description:
      "Craft resumes that pass ATS filters and impress humans — with strong bullets, honest framing, and targeted content.",
    topics: [
      "Resume structure",
      "Action verbs",
      "Quantifying achievements",
      "ATS optimization",
      "Tailoring to job descriptions",
      "Gaps in work history",
      "Cover letters",
      "LinkedIn profile basics",
    ],
    environment: "office-desk",
    available: true,
  },
  {
    slug: "networking-coach",
    title: "Networking Coach",
    category: "life-advice",
    tagline: "Build real connections, not just contacts.",
    description:
      "Navigate professional networking — reaching out cold, following up well, attending events, and turning contacts into opportunities.",
    topics: [
      "Cold outreach",
      "Informational interviews",
      "Following up",
      "Networking events",
      "LinkedIn strategy",
      "Elevator pitch",
      "Asking for referrals",
      "Building long-term relationships",
    ],
    environment: "office-desk",
    available: true,
  },
  {
    slug: "career-counselor",
    title: "Career Counselor",
    category: "life-advice",
    tagline: "Choose a path, navigate pivots, find work that fits your life.",
    description:
      "Explore career paths, weigh job offers, plan pivots, and make decisions about education, training, and work that align with your values.",
    topics: [
      "Career exploration",
      "Job offer evaluation",
      "Salary negotiation",
      "Career pivots",
      "Education vs experience tradeoffs",
      "Work-life balance",
      "Internship strategy",
      "Professional development",
    ],
    environment: "office-desk",
    available: true,
  },

  // CREATIVE & DESIGN
  {
    slug: "architect",
    title: "Architect",
    category: "creative-design",
    tagline: "Design buildings, solve spatial problems, shape communities.",
    description:
      "Develop building plans, balance aesthetics with structural requirements, and guide projects from concept sketch to construction.",
    topics: [
      "Floor plan design",
      "Structural load basics",
      "Zoning and code compliance",
      "Client brief interpretation",
      "Sustainable materials",
      "3D modeling concepts",
      "Project budget tradeoffs",
    ],
    environment: "mech-lab",
    available: true,
  },
  {
    slug: "fashion-designer",
    title: "Fashion Designer",
    category: "creative-design",
    tagline: "Sketch collections, source fabrics, bring clothing to life.",
    description:
      "Create original clothing designs, select materials, manage production timelines, and understand market trends.",
    topics: [
      "Sketching and illustration",
      "Fabric selection",
      "Trend forecasting",
      "Pattern construction",
      "Sustainable fashion",
      "Brand identity",
      "Production and sourcing",
    ],
    environment: "office-desk",
    available: true,
  },
  {
    slug: "art-director",
    title: "Art Director",
    category: "creative-design",
    tagline: "Lead visual identity, direct shoots, make campaigns unforgettable.",
    description:
      "Oversee the visual style of campaigns, coordinate creative teams, and translate brand strategy into compelling imagery.",
    topics: [
      "Visual hierarchy",
      "Typography and color theory",
      "Photo and video direction",
      "Brand guidelines",
      "Client presentations",
      "Creative brief development",
      "Feedback and revision cycles",
    ],
    environment: "office-desk",
    available: true,
  },
  {
    slug: "gallery-curator",
    title: "Gallery Curator",
    category: "creative-design",
    tagline: "Select art, design exhibitions, connect artists with audiences.",
    description:
      "Research and acquire works, design exhibition layouts, write interpretive content, and manage artist relationships.",
    topics: [
      "Art history and criticism",
      "Exhibition planning",
      "Artist research",
      "Grant writing",
      "Collection management",
      "Community outreach",
      "Budget allocation",
    ],
    environment: "office-desk",
    available: true,
  },
  {
    slug: "interior-designer",
    title: "Interior Designer",
    category: "creative-design",
    tagline: "Transform spaces, balance function with beauty, delight clients.",
    description:
      "Plan room layouts, select furniture and materials, manage contractors, and deliver spaces that are both beautiful and functional.",
    topics: [
      "Space planning",
      "Color and material selection",
      "Client needs assessment",
      "Lighting design",
      "Building codes",
      "Budget management",
      "CAD basics",
    ],
    environment: "mech-lab",
    available: true,
  },
  {
    slug: "urban-planner",
    title: "Urban Planner",
    category: "creative-design",
    tagline: "Shape cities, design public spaces, solve growth challenges.",
    description:
      "Analyze land use, develop zoning plans, engage communities, and design the infrastructure that makes cities livable.",
    topics: [
      "Land use analysis",
      "Zoning and regulation",
      "Transit and mobility",
      "Community engagement",
      "Environmental impact",
      "GIS mapping basics",
      "Housing policy",
    ],
    environment: "construction-site",
    available: true,
  },
  {
    slug: "social-media-manager",
    title: "Social Media Manager",
    category: "creative-design",
    tagline: "Build audiences, create content, measure what works.",
    description:
      "Develop content strategies, manage brand presence across platforms, analyze engagement data, and drive growth.",
    topics: [
      "Content calendar planning",
      "Platform algorithms",
      "Copywriting and visual design",
      "Community management",
      "Analytics and KPIs",
      "Paid social basics",
      "Brand voice",
    ],
    environment: "office-desk",
    available: true,
  },
  {
    slug: "brand-strategist",
    title: "Brand Strategist",
    category: "creative-design",
    tagline: "Define positioning, shape perception, build brand equity.",
    description:
      "Research competitors, define brand identity, develop messaging frameworks, and ensure consistent communication across all channels.",
    topics: [
      "Market research",
      "Brand positioning",
      "Competitive analysis",
      "Messaging hierarchy",
      "Visual identity systems",
      "Customer personas",
      "Brand audit",
    ],
    environment: "office-desk",
    available: true,
  },
  {
    slug: "graphic-designer",
    title: "Graphic Designer",
    category: "creative-design",
    tagline: "Communicate visually, solve design problems, craft great work.",
    description:
      "Create logos, layouts, and visual assets across print and digital — balancing aesthetics with clear communication goals.",
    topics: [
      "Layout and composition",
      "Typography",
      "Color theory",
      "Logo design",
      "Print production",
      "Digital design tools",
      "Client feedback",
    ],
    environment: "office-desk",
    available: true,
  },
  {
    slug: "film-video-producer",
    title: "Film & Video Producer",
    category: "creative-design",
    tagline: "Develop stories, manage productions, bring vision to screen.",
    description:
      "Develop scripts, manage production budgets, coordinate crew and talent, and oversee post-production from edit to final delivery.",
    topics: [
      "Script development",
      "Production budgeting",
      "Crew coordination",
      "Directing basics",
      "Post-production workflow",
      "Distribution strategy",
      "Rights and licensing",
    ],
    environment: "office-desk",
    available: true,
  },
];

export function getSimulation(slug: string): SimulationDefinition | undefined {
  return SIMULATIONS.find((s) => s.slug === slug);
}
